COPYPATH("SOUNDING", "1:/LAUNCH").
COPYPATH("FIRE_SHORT", "1:/FIRE_SHORT").
COPYPATH("GRAVITY_TURN", "1:/GRAVITY_TURN").
COPYPATH("COUNTDOWN", "1:/COUNTDOWN").
COPYPATH("STAGE_FLAMEOUT", "1:/STAGE_FLAMEOUT").
COPYPATH("FIRE_LONG", "1:/FIRE_LONG").
SWITCH TO 1.
LIST FILES.